import '../core/constants.dart';
import '../models/booking.dart';

final DateTime _today = DateTime.now();

final List<BookingItem> mockBookings = [
  BookingItem(
    id: 'b1',
    userId: 'u1',
    userName: 'Vishesh Sharma',
    resourceId: 'r1',
    resourceName: 'AgroMax 5310',
    ownerId: 'o1',
    startDate: _today.add(const Duration(days: 3)),
    endDate: _today.add(const Duration(days: 5)),
    rentalAmount: 5000,
    deposit: 5000,
    status: BookingStatus.pending,
    location: 'Karnal, Haryana',
    requestDate: _today.subtract(const Duration(hours: 6)),
  ),
  BookingItem(
    id: 'b2',
    userId: 'u1',
    userName: 'Vishesh Sharma',
    resourceId: 'r2',
    resourceName: 'FieldKing Harvester',
    ownerId: 'o2',
    startDate: _today.add(const Duration(days: 10)),
    endDate: _today.add(const Duration(days: 12)),
    rentalAmount: 14000,
    deposit: 10000,
    status: BookingStatus.approved,
    location: 'Panipat, Haryana',
    requestDate: _today.subtract(const Duration(days: 1)),
  ),
  BookingItem(
    id: 'b3',
    userId: 'u2',
    userName: 'Meena Kumari',
    resourceId: 'r4',
    resourceName: 'TerraHaul Truck 407',
    ownerId: 'o3',
    startDate: _today.subtract(const Duration(days: 5)),
    endDate: _today.subtract(const Duration(days: 2)),
    rentalAmount: 9900,
    deposit: 6000,
    status: BookingStatus.completed,
    location: 'Karnal, Haryana',
    requestDate: _today.subtract(const Duration(days: 8)),
  ),
  BookingItem(
    id: 'b4',
    userId: 'u1',
    userName: 'Vishesh Sharma',
    resourceId: 'r5',
    resourceName: 'PowerTrac 575 DI',
    ownerId: 'o4',
    startDate: _today,
    endDate: _today.add(const Duration(days: 2)),
    rentalAmount: 6600,
    deposit: 4500,
    status: BookingStatus.active,
    location: 'Karnal, Haryana',
    requestDate: _today.subtract(const Duration(days: 2)),
  ),
  BookingItem(
    id: 'b5',
    userId: 'u3',
    userName: 'Ravi Chauhan',
    resourceId: 'r3',
    resourceName: 'GreenLine Cultivator',
    ownerId: 'o1',
    startDate: _today.add(const Duration(days: 20)),
    endDate: _today.add(const Duration(days: 22)),
    rentalAmount: 2400,
    deposit: 2000,
    status: BookingStatus.rejected,
    location: 'Kurukshetra, Haryana',
    requestDate: _today.subtract(const Duration(days: 3)),
    rejectionReason: 'Resource under maintenance for those dates',
  ),
  BookingItem(
    id: 'b6',
    userId: 'u1',
    userName: 'Vishesh Sharma',
    resourceId: 'r7',
    resourceName: 'HydroFlow Irrigation Pump',
    ownerId: 'o6',
    startDate: _today.add(const Duration(days: 15)),
    endDate: _today.add(const Duration(days: 16)),
    rentalAmount: 1600,
    deposit: 1500,
    status: BookingStatus.cancelled,
    location: 'Kaithal, Haryana',
    requestDate: _today.subtract(const Duration(days: 4)),
  ),
  BookingItem(
    id: 'b7',
    userId: 'u4',
    userName: 'Simran Kaur',
    resourceId: 'r9',
    resourceName: 'SeedMaster Seeder',
    ownerId: 'o8',
    startDate: _today.add(const Duration(days: 7)),
    endDate: _today.add(const Duration(days: 8)),
    rentalAmount: 1500,
    deposit: 2500,
    status: BookingStatus.paymentPending,
    location: 'Panipat, Haryana',
    requestDate: _today.subtract(const Duration(hours: 20)),
  ),
];
