import '../core/constants.dart';
import '../models/resource.dart';

final List<ResourceItem> mockResources = [
  ResourceItem(
    id: 'r1',
    ownerId: 'o1',
    ownerName: 'Ramesh Kumar',
    categoryId: 'tractor',
    name: 'AgroMax 5310',
    description:
        'Reliable mid-range tractor, well maintained, ideal for ploughing and tilling on medium farms.',
    imageEmojis: ['🚜'],
    location: 'Karnal, Haryana',
    distanceKm: 2.5,
    price: 2500,
    pricingType: PricingType.daily,
    rating: 4.8,
    reviewCount: 120,
    status: ResourceStatus.listed,
    specs: {'Horsepower': '53 HP', 'Model': '2022', 'Fuel': 'Diesel'},
    securityDeposit: 5000,
    availableDateRange: ['15 Sept', '30 Sept'],
  ),
  ResourceItem(
    id: 'r2',
    ownerId: 'o2',
    ownerName: 'Suresh Yadav',
    categoryId: 'harvester',
    name: 'FieldKing Harvester',
    description:
        'High-capacity combine harvester suited for wheat and paddy, operator available on request.',
    imageEmojis: ['🌾'],
    location: 'Panipat, Haryana',
    distanceKm: 6.1,
    price: 7000,
    pricingType: PricingType.daily,
    rating: 4.6,
    reviewCount: 98,
    status: ResourceStatus.listed,
    specs: {'Type': 'Combine', 'Capacity': 'Large', 'Fuel': 'Diesel'},
    securityDeposit: 10000,
    availableDateRange: ['20 Sept', '10 Oct'],
  ),
  ResourceItem(
    id: 'r3',
    ownerId: 'o1',
    ownerName: 'Ramesh Kumar',
    categoryId: 'equipment',
    name: 'GreenLine Cultivator',
    description: '9-tine cultivator, great for soil preparation before sowing.',
    imageEmojis: ['🌱'],
    location: 'Kurukshetra, Haryana',
    distanceKm: 4.2,
    price: 1200,
    pricingType: PricingType.daily,
    rating: 4.5,
    reviewCount: 64,
    status: ResourceStatus.listed,
    specs: {'Type': 'Cultivator', 'Tines': '9', 'Width': '7 ft'},
    securityDeposit: 2000,
    availableDateRange: ['1 Oct', '20 Oct'],
  ),
  ResourceItem(
    id: 'r4',
    ownerId: 'o3',
    ownerName: 'Vikram Patel',
    categoryId: 'truck',
    name: 'TerraHaul Truck 407',
    description: 'Sturdy load carrier for transporting produce, feed, and equipment.',
    imageEmojis: ['🚛'],
    location: 'Karnal, Haryana',
    distanceKm: 3.3,
    price: 3300,
    pricingType: PricingType.daily,
    rating: 4.4,
    reviewCount: 52,
    status: ResourceStatus.listed,
    specs: {'Load Capacity': '5 Ton', 'Model': '2021', 'Fuel': 'Diesel'},
    securityDeposit: 6000,
    availableDateRange: ['12 Sept', '28 Sept'],
  ),
  ResourceItem(
    id: 'r5',
    ownerId: 'o4',
    ownerName: 'Sandeep Yadav',
    categoryId: 'tractor',
    name: 'PowerTrac 575 DI',
    description: 'Fuel-efficient tractor with strong torque, good for hauling trolleys too.',
    imageEmojis: ['🚜'],
    location: 'Karnal, Haryana',
    distanceKm: 3.2,
    price: 2200,
    pricingType: PricingType.daily,
    rating: 4.7,
    reviewCount: 86,
    status: ResourceStatus.listed,
    specs: {'Horsepower': '57 HP', 'Model': '2023', 'Fuel': 'Diesel'},
    securityDeposit: 4500,
    availableDateRange: ['5 Sept', '25 Sept'],
  ),
  ResourceItem(
    id: 'r6',
    ownerId: 'o5',
    ownerName: 'Ritika Singh',
    categoryId: 'land',
    name: 'Agricultural Land (2 Acres)',
    description: 'Fertile field, canal-irrigated, suitable for wheat and sugarcane rotation.',
    imageEmojis: ['🌾'],
    location: 'Karnal, Haryana',
    distanceKm: 5.8,
    price: 15000,
    pricingType: PricingType.monthly,
    rating: 4.6,
    reviewCount: 42,
    status: ResourceStatus.listed,
    specs: {
      'Area': '2 Acres',
      'Soil type': 'Loamy',
      'Irrigation': 'Canal',
      'Crop suitability': 'Wheat, Sugarcane',
    },
    securityDeposit: 20000,
    availableDateRange: ['1 Oct', '31 Mar'],
  ),
  ResourceItem(
    id: 'r7',
    ownerId: 'o6',
    ownerName: 'Amit Sharma',
    categoryId: 'irrigation',
    name: 'HydroFlow Irrigation Pump',
    description: 'Diesel-powered irrigation pump with 3-inch outlet, portable.',
    imageEmojis: ['💧'],
    location: 'Kaithal, Haryana',
    distanceKm: 8.4,
    price: 800,
    pricingType: PricingType.daily,
    rating: 4.3,
    reviewCount: 31,
    status: ResourceStatus.listed,
    specs: {'Type': 'Diesel Pump', 'Power source': 'Diesel', 'Coverage area': '5 Acres'},
    securityDeposit: 1500,
    availableDateRange: ['10 Sept', '30 Sept'],
  ),
  ResourceItem(
    id: 'r8',
    ownerId: 'o7',
    ownerName: 'Vikram Patel',
    categoryId: 'tools',
    name: 'FarmHand Tool Kit',
    description: 'Complete set of hand tools for maintenance and small repairs.',
    imageEmojis: ['🔧'],
    location: 'Jind, Haryana',
    distanceKm: 12.1,
    price: 300,
    pricingType: PricingType.daily,
    rating: 4.2,
    reviewCount: 18,
    status: ResourceStatus.listed,
    specs: {'Pieces': '24', 'Case': 'Included'},
    securityDeposit: 500,
    availableDateRange: ['1 Sept', '30 Sept'],
  ),
  ResourceItem(
    id: 'r9',
    ownerId: 'o8',
    ownerName: 'Manoj Verma',
    categoryId: 'equipment',
    name: 'SeedMaster Seeder',
    description: 'Precision seed drill for uniform sowing across row crops.',
    imageEmojis: ['🌾'],
    location: 'Panipat, Haryana',
    distanceKm: 7.6,
    price: 1500,
    pricingType: PricingType.daily,
    rating: 4.4,
    reviewCount: 27,
    status: ResourceStatus.listed,
    specs: {'Type': 'Seed Drill', 'Rows': '9', 'Width': '9 ft'},
    securityDeposit: 2500,
    availableDateRange: ['15 Sept', '5 Oct'],
  ),
  ResourceItem(
    id: 'r10',
    ownerId: 'o9',
    ownerName: 'Deepak Chauhan',
    categoryId: 'equipment',
    name: 'SprayPro Boom Sprayer',
    description: 'Tractor-mounted boom sprayer for pesticide and fertilizer application.',
    imageEmojis: ['🚿'],
    location: 'Kurukshetra, Haryana',
    distanceKm: 9.9,
    price: 1100,
    pricingType: PricingType.daily,
    rating: 4.1,
    reviewCount: 15,
    status: ResourceStatus.listed,
    specs: {'Type': 'Boom Sprayer', 'Tank': '400L', 'Width': '12 ft'},
    securityDeposit: 2000,
    availableDateRange: ['1 Oct', '15 Oct'],
  ),
  ResourceItem(
    id: 'r11',
    ownerId: 'o10',
    ownerName: 'Anita Devi',
    categoryId: 'truck',
    name: 'CargoKing Mini Truck',
    description: 'Compact truck for short-haul deliveries between farm and market.',
    imageEmojis: ['🚚'],
    location: 'Karnal, Haryana',
    distanceKm: 4.9,
    price: 1800,
    pricingType: PricingType.daily,
    rating: 4.3,
    reviewCount: 22,
    status: ResourceStatus.pendingApproval,
    specs: {'Load Capacity': '1.5 Ton', 'Model': '2020', 'Fuel': 'Diesel'},
    securityDeposit: 3000,
    availableDateRange: ['20 Sept', '10 Oct'],
  ),
  ResourceItem(
    id: 'r12',
    ownerId: 'o11',
    ownerName: 'Harpreet Singh',
    categoryId: 'harvester',
    name: 'CropCutter Mini Harvester',
    description: 'Compact harvester suited for smaller landholdings and mixed crops.',
    imageEmojis: ['🌾'],
    location: 'Yamunanagar, Haryana',
    distanceKm: 14.3,
    price: 5200,
    pricingType: PricingType.daily,
    rating: 4.0,
    reviewCount: 11,
    status: ResourceStatus.listed,
    specs: {'Type': 'Mini Combine', 'Capacity': 'Medium', 'Fuel': 'Diesel'},
    securityDeposit: 8000,
    availableDateRange: ['25 Sept', '15 Oct'],
  ),
  ResourceItem(
    id: 'r13',
    ownerId: 'o12',
    ownerName: 'Sunita Rani',
    categoryId: 'land',
    name: 'Riverside Farmland (5 Acres)',
    description: 'Large plot near the river, good for seasonal lease, water access included.',
    imageEmojis: ['🌾'],
    location: 'Panipat, Haryana',
    distanceKm: 11.2,
    price: 32000,
    pricingType: PricingType.monthly,
    rating: 4.5,
    reviewCount: 9,
    status: ResourceStatus.listed,
    specs: {
      'Area': '5 Acres',
      'Soil type': 'Alluvial',
      'Irrigation': 'River-fed',
      'Crop suitability': 'Rice, Vegetables',
    },
    securityDeposit: 40000,
    availableDateRange: ['1 Nov', '30 Apr'],
  ),
  ResourceItem(
    id: 'r14',
    ownerId: 'o13',
    ownerName: 'Kuldeep Malik',
    categoryId: 'tractor',
    name: 'TerraForce 6045',
    description: 'Heavy-duty tractor for large farms, works well with rotavators and trolleys.',
    imageEmojis: ['🚜'],
    location: 'Sonipat, Haryana',
    distanceKm: 16.5,
    price: 3100,
    pricingType: PricingType.daily,
    rating: 4.6,
    reviewCount: 40,
    status: ResourceStatus.listed,
    specs: {'Horsepower': '60 HP', 'Model': '2022', 'Fuel': 'Diesel'},
    securityDeposit: 6000,
    availableDateRange: ['10 Sept', '30 Sept'],
  ),
  ResourceItem(
    id: 'r15',
    ownerId: 'o14',
    ownerName: 'Preeti Kaur',
    categoryId: 'irrigation',
    name: 'AquaLine Sprinkler Set',
    description: 'Portable sprinkler irrigation set covering up to 3 acres.',
    imageEmojis: ['💧'],
    location: 'Ambala, Haryana',
    distanceKm: 19.8,
    price: 650,
    pricingType: PricingType.daily,
    rating: 4.2,
    reviewCount: 13,
    status: ResourceStatus.listed,
    specs: {'Type': 'Sprinkler', 'Power source': 'Electric', 'Coverage area': '3 Acres'},
    securityDeposit: 1200,
    availableDateRange: ['1 Sept', '20 Sept'],
  ),
];

ResourceItem? findResourceById(String id) {
  try {
    return mockResources.firstWhere((r) => r.id == id);
  } catch (_) {
    return null;
  }
}
